version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mariadb
    restart: always
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ss1234
    volumes:
      - ./Database:/docker-entrypoint-initdb.d/:ro