version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mariadb/server:10.4 
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ss1234